services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html:delegated
    env_file:
      - .env.docker
    extra_hosts:
      - "host.docker.internal:host-gateway"