services:
  - type: web
    name: techsubs-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    branch: develop
    healthCheckPath: /health
    envVars:
      - key: APP_NAME
        value: TechSubs
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        value: base64:M5qp4JA4shYaH36xXqpAoVKT1iQOzqKWAVHQ4ytMXcM=
      - key: APP_URL
        fromService:
          type: web
          name: techsubs-api
          property: host
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: debug
      - key: LOG_STACK
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-frosty-mountain-aglbvim1-pooler.c-2.eu-central-1.aws.neon.tech
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_uSMi3XZ5TdQn
      - key: DB_SSLMODE
        value: require
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_uSMi3XZ5TdQn@ep-frosty-mountain-aglbvim1-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: SESSION_DOMAIN
        value: null
      - key: ASSET_URL
        fromService:
          type: web
          name: techsubs-api
          property: host
      - key: TRUSTED_PROXIES
        value: "*"
      - key: PASSPORT_PRIVATE_KEY
        value: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tDQpNSUlKUWdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0NTd3dnZ2tvQWdFQUFvSUNBUUNwRXN1MzlhaDMvMXZPDQpwUnBmV2o4OFlMc0RaSGEwRStkbHF0ZkhZVEU5eHEvdnp1VXFlN0NxcStzTUhxNFRhNUt3djdLcXJObWIzOXBJDQpJNThxSWhVaW44aXYvSm9PODNjUDNDUHY1SnpHb0Y4bGpvMzdrREJMQW9XM2R0MXRuUXptOXh0Z3FRRnNudEI2DQpWMmFuRVQ0bkdpZzlNZmhBeGVsUHRWK2FHZzMxSU03VC93RHViRTdEbkl6bC9SLzRuU3pLV2IvMjBkYnVnOXRoDQo3eEx2azUwZmhBSnVuK1J2L1pZcUkweFRBc3E1aCtETzF6d0p5b0RteGNqUllpUG5HVzhJcHcyQWlCOGcvUG1hDQpWSEtaUnhVdU5IUW01K3JqZUFMT0l3WVZtMHlPWEdIRHBYanB5SVF4K1QwZmZUL0FxNWRCS1dIejJSWll5WUx3DQp5bjhjOXpiWCtTWjd6a09zUzM2aWw0amZWelNYYmowM2hOREtWZ3R4WUlNS2JwMHNQckYvSzYxbDhxUldRWFBQDQpHTWc1cTJHVkxPZ2JJcktqS1RnRm9qd3hLaDVVQ3JVcnFPWUJjTTdjQkFUNkgxOWR6d29EZ3Q0dldJc09lVHA1DQpTRFVBYmZUbjNaTUdFRFVjTXlxMnlxbW1rd2h2VnZUU25xeHllOE5UMHlxWTdxQWtpTnNHWUJ2L0pJVG1VYmZ4DQpKdFN2T2dhek9POVIzN2Q5WElVVHJJMUpaUlJadkNYMEpmb3FpWlJ5OFROQlIyMndaclF6cEk5S20zd3R3TXZKDQP1QnZOOFNzY1ExZXNPRVJCT1dEMHlYRFk2cTBkZXNucVRWM1JIYWRQNG50WFJpb0t4dXZ5ZmZ1OFBFY0Q4RkN5DQpxOFJPeXpiKzNqSnZNWkxJVlg3c0t6bGpzVUtWK1FJREFRQUJBb0lDQUJNVDV0N2NIbVZqOEJVU05qYWFOVlozDQp4OEpyUEtXM05UNFlsLzZNYmdUOWZXNisxc2NEYS96bUowQ1gyYWFoVmMwUjVIUXp5dDQyMVNlY3RXSUl0SC9TDQpyYytGM2xCZmtvaThNMlYvVTExcVRUSXNzc0szRTJ2elhkbEV4Vm1RQmh1dHVHNGd3K05nekQ5eHkwaUF2cFdrDQo4dk5zeHdsd0M1S044YnF1dy9Kc0FFcVZsS0pTb0ZTY1BwM1pBUm1KaXJ0T2cwV3ppZUFpQ3NnekROekp1RW9ODQpHRVVwVDVwL2I4bFRjRkpSbDFSMkM1enJWbi80VkxFMWtpSm1RNHpaSnRsQUdGcnZnU3UwditsMUsvVTF1eU1hDQpraHl0d0tob0sxRGRUTnQxU1o4cXQzRmZJNVNscHAwSTlhZXU5MW1qUXc3OFAyeEhpNmo3SEFaVm95QSttUFo0DQpra0VkcFRyaGl1QUhTWmdsby8xR3FOeTlNNTl0ejhQdUVCL1FSMVMoamxZREpBWmg1bUh4d290aGxHWm42b2FNDQpjSGttTEVaRkx1TWgzQm4waFpjVjJGMkpYdjdmV0lCVUFPbHJBdkdzZ1U0MGJkVFhSZkp1TTZXekVqTkF6Y0hKDQpubnJuS0M5WkVoS2U2L1JDbm11bmZiQjh0RUJNaDRvNDBscmRCZGt4S1h1NlBMeUkzeE9sMDZkWDhVenpnWG5QDQpaZ2FuMkdGREFJeVMwemFQNFJNUUpudUZYOFNWcmFraUNHMVQwT1lMZ0VESlE4WitpY0lMMWdiNXBOOXRUUVFCDQp6bGowa3d3b1RkYk9DbmJlY1VyM0wrNzdJWWpOcGhWSGpnY1pSdGgyZFBnU3lnZWtNa0Y3ZktGOHFoNFZVcGE2DQp5bW1MYzBnWEU0ZnNyNFd3NUdoZEFvSUJBUURudXJUYTZkR3hQUUt5SDFUM3dKVlpmQTZkMzRKOWJ3WkFsNUhSDQpYdXlQREh6TklzS1N4RGw5LzN0YVRQNWJJMWk1YzN3SzFFUEE3ZUs3aVhJSUkwQUNBamdNS0ZUUFBwRVFhZDJDDQp2RDByeEdyTHA0SHl1Tm00c1Z2cEQ4c2VSSGV3NXAxZ2RKNmg0T0pkRjJJKzJzSGN2UzgvYklUUHRkMndUK3piDQo1SVBhbmU1Sk5URHNmeFZJNFE1Ujl3UzgxSnRsKzFWMDlEUUc2ZWdXR2o5KzFmbUZsRGExdFJRcnpId3ZMeU9XDQpNOEd0d3gweCsvaEJJTVQzZUlLYVFHbzc4aHNrZlQ2QS9XQ3RJWGs4eEg4dkdzU3JDZE85azN2ZlZkUWJYVUhlDQp5NHgxOWhkbGFwZ2FoT2hLRXlQaXhhcjZWYi9uVzF1YnpIcjZvSDIvcDQzSzUzOG5Bb0lCQVFDNnlCMDQyaGhuDQpUcDhHYXBCalpaYzF6MWJmWWgwTEU4cExvL1JrNmlsQjhBcVhoWDhoMEVOQTlsanV0amlqRFR4UVVVcHVEWUhODQpROHBTajAzZ01BNndEN2J2b2UvWThJSG9UK2dyRStPZ0ZuVDI2TS9vZ3VnUmIyV2hEN3ZmQ3J4c3h0Ykl4eFhHDQpJckFDbFBYMzdydVI2elBSdlk2VmhaZ3dEdXZ1SnRVRnpIeFJkWXNicngxNWNQYitQeWRsdnBpMkRYOWhuMWxyDQpKU003VjV1YWNWN0FYVmI1YXBSL3NyL21JMHRZVWNvRGRzVzhNRURjS25CemVGdzEyajZnUTNMSERMeWM3cmJqDQo1cHlPWXR3U21INnF2MGs5ZkU1cTEwalZLV3BxUG96UGl4dzRoQXBuSXVCYmtNZkJrTVZxTGY0QiszTEtEY1VFDQpWa2RkRlhtR1VuWGZBb0lCQUhhU1JJUlhiQ0tpczBSdFg4Njl6aTNSbXJFUmN2VzMzNTBoY1UyT29zQzNoUXg2DQpJdEZ5Y25DVVQ0dnZKWitBd0o5MEJoNk1hbmJId21KdmU5ZktJYkJsYmtSYVJyc2NxcUdaYWV6QllST0tGNU5KDQpqT2FqeTFRRC9LR09vVUpGaW5FTUw2N3hQVkpiZmJoZ2hMYmd2SjIwZC82ZUNuODE4YytMdGdqMkxybW9ZZ3MzDQptbWNJeDkxWXV6a1ppbVVNN004TUFiZ3NWSXJOR1NKbUgrTkluYnJLRWd4OE1Xd1AzK05NM1lxM3hQeWlmOGZaDQp4RGVmQ3VvTjBkWVg2OFBzcUJMTnV6UEpjclJrRXNWUnpqcE9HaC9pa1dQSm1YSzN1aWFlVzF3akR5WTAyOWZhDQo2U1Y0cUZ0dTI4Zm5tUXNxNFYwQ2xDZHVRK2NHUkJIVExHeU1jN1VDZ2dFQkFMRGZSeXpLK2tqNW5vV0k2K256DQpsS01VRUlQQWVSaEFTVlNQa2FMdVN0dHgzOVhVU0t0UWVCOVFLSzhFUjJXLzV0bDM0UytPQXRqSjFSR1JPb0dODQpnSnNnaG04dHZkNkZBYjlueThiZk1ySXFFZUN1WGhNanczYWZNbkh1WUUyNThPeGc3b3Q2V3hnaFNPTnBBL01nDQpVdWErLzNjaU5aOUp2dS9qY1c4M3ZvbWJOaTQ5VE5tT1hpN2Qxa2Ewcnk0ZDZxYWE2WUVjVUtTeHFrZExrc0lSDQprVlJBRDFob29PNjc2aFNZWDRUbkRwRnhLNVlsYTRZUmVpTWVXdE4wTTlHM2pUMEl4cU1sT25OZHNlcnptc3JSDQpOVUdqbWt0ckp5YnRicjdNVlVUK3JvRHFqbkxHTnNPcnR5RitYR3JrR00yUGQvV1Frd2JiT3pIOE1kL25zZ2lNDQpsYWtDZ2dFQVlDRmNUTWFQNkx2SGdKRzNtdzdqQXpqZEtiVkVUZnUzQnZDUzNlL0RzZllkdEVtYlNJeTBCR3JSDQpLT3M1NVg3UjRESGttelp3MVRYYnJuUzliQ1NUOG9yczRFVFNkbHE3ZUZPaVYyYmIvS0RGRzJxUDE4MFBTVFhYDQpHYitwR1ZseC9BRklPTk1YNTZHaWxXQWh6dngyaFdxWDl2MHErc2duWEc4b1IwVlB3b21OUm1RcFYyankzTk9nDQozNXR4YXg0TkRDdEhhZnRBTTB6RFJHazA5UGdBVmhHekZydVhlTlhUVXZpVVV1bGFJTEJWdUVWL2dCNEUwVVlHDQpsRE1EeHlHUXRZN3JHaDVRamN4NnMvOUlFaDhWc1ZGTm9xbWNuTE5DTHNPNHY2YUx3d2taRXB0VWRpRWw4QWE4DQp1Z1ErenFzMktFbTB6V2NEUDlaaVVHWHBKTEE1Z0E9PQ0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQ==
      - key: PASSPORT_PUBLIC_KEY
        value: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0NCk1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBcVJMTHQvV29kLzlienFVYVgxby8NClBHQzdBMlIydEJQblphclh4MkV4UGNhdjc4N2xLbnV3cXF2ckRCNnVFMnVTc0wreXFxelptOS9hU0NPZktpSVYNCklwL0lyL3lhRHZOM0Q5d2o3K1NjeHFCZkpZNk4rNUF3U3dLRnQzYmRiWjBNNXZjYllLa0JiSjdRZWxkbXB4RSsNCkp4b29QVEg0UU1YcFQ3VmZtaG9OOVNETzAvOEE3bXhPdzV5TTVmMGYrSjBzeWxtLzl0SFc3b1BiWWU4Uzc1T2QNCkg0UUNicC9rYi8yV0tpTk1Vd0xLdVlmZ3p0YzhDY3FBNXNYSTBXSWo1eGx2Q0tjTmdJZ2ZJUHo1bWxSeW1VY1YNCkxqUjBKdWZxNDNnQ3ppTUdGWnRNamx4aHc2VjQ2Y2lFTWZrOUgzMC93S3VYUVNsaDg5a1dXTW1DOE1wL0hQYzINCjEva21lODVEckV0K29wZUkzMWMwbDI0OU40VFF5bFlMY1dDRENtNmRMRDZ4Znl1dFpmS2tWa0Z6enhqSU9hdGgNCmxTem9HeUt5b3lrNEJhSThNU29lVkFxMUs2am1BWERPM0FRRStoOWZYYzhLQTRMZUwxaUxEbms2ZVVnMUFHMzANCjU5MlRCaEExSERNcXRzcXBwcE1JYjFiMDBwNnNjbnZEVTlNcW1PNmdKSWpiQm1BYi95U0U1bEczOFNiVXJ6b0cNCnN6anZVZCszZlZ5RkU2eU5TV1VVV2J3bDlDWDZLb21VY3ZFelFVZHRzR2EwTTZTUFNwdDhMY0RMeWJnYnpmRXINCkhFTlhyRGhFUVRsZzlNbHcyT3F0SFhySjZrMWQwUjJuVCtKN1YwWXFDc2JyOG4zN3ZEeEhBL0JRc3F2RVRzczINCi90NHliekdTeUZWKzdDczVZN0ZDbGZrQ0F3RUFBUT09DQotLS0tLUVORCBQVUJMSUMgS0VZLS0tLS0=
      - key: FORCE_CLEAN_DB
        value: "true"
      - key: CORS_ALLOWED_ORIGINS
        value: https://techsubs.vercel.app,http://localhost:3000,http://localhost:5173