services:
  - type: web
    name: techsubs-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    branch: main
    healthCheckPath: /health
    buildCommand: php artisan storage:link
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_NAME
        value: TechSubs
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:M5qp4JA4shYaH36xXqpAoVKT1iQOzqKWAVHQ4ytMXcM=
      - key: APP_URL
        fromService:
          type: web
          name: techsubs-api
          property: host
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-spring-boat-ag8g7v2p-pooler.c-2.eu-central-1.aws.neon.tech
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_fuMPB4IvaN6G